name: Build and Test the Prog8 compiler

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build and install recent 64tass
        run: |
          sudo apt-get install -y make build-essential
          git clone --depth=1 https://github.com/irmen/64tass
          cd 64tass
          make -j4
          sudo make install          

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build and test with Gradle
        run: |
          ./gradlew build shadowJar --no-daemon
          sha256sum -b compiler/build/libs/*-all.jar > compiler/build/libs/hash.txt
        
      - name: Create compiler shadowJar artifact
        uses: actions/upload-artifact@v4
        with:
          name: prog8-compiler-jar-zipped
          path: |
            compiler/build/libs/*-all.jar
            compiler/build/libs/hash.txt

